[package]
name = "portal"
version = "0.1.0"
authors = ["moop"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termcolor = "1.1.0" 
clap = "2.33.0"
scoped_threadpool = "0.1.*"
